# Generated by Django 4.0.3 on 2022-03-15 18:39

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 15, 19, 39, 41, 698573)),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('5', '5'), ('4', '4'), ('3', '3'), ('6', '6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Reversing Camera', 'Reversing Camera'), ('Power Steering', 'Power Steering'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Wind Deflector', 'Wind Deflector'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Alarm System', 'Alarm System'), ('Seat Heating', 'Seat Heating'), ('ParkAssist', 'ParkAssist'), ('Audio Interface', 'Audio Interface'), ('Cruise Control', 'Cruise Control')], max_length=195),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('FL', 'Florida'), ('KS', 'Kansas'), ('HI', 'Hawaii'), ('MI', 'Michigan'), ('AZ', 'Arizona'), ('SD', 'South Dakota'), ('NE', 'Nebraska'), ('LA', 'Louisiana'), ('DC', 'District Of Columbia'), ('MA', 'Massachusetts'), ('AR', 'Arkansas'), ('CO', 'Colorado'), ('OH', 'Ohio'), ('ID', 'Idaho'), ('DE', 'Delaware'), ('IN', 'Indiana'), ('KY', 'Kentucky'), ('NJ', 'New Jersey'), ('AL', 'Alabama'), ('ND', 'North Dakota'), ('MO', 'Missouri'), ('WA', 'Washington'), ('VA', 'Virginia'), ('NC', 'North Carolina'), ('OK', 'Oklahoma'), ('MD', 'Maryland'), ('GA', 'Georgia'), ('NV', 'Nevada'), ('TN', 'Tennessee'), ('WI', 'Wisconsin'), ('PA', 'Pennsylvania'), ('CA', 'California'), ('NM', 'New Mexico'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('MN', 'Minnesota'), ('RI', 'Rhode Island'), ('WY', 'Wyoming'), ('AK', 'Alaska'), ('WV', 'West Virginia'), ('NH', 'New Hampshire'), ('IA', 'Iowa'), ('UT', 'Utah'), ('OR', 'Oregon'), ('SC', 'South Carolina'), ('NY', 'New York'), ('IL', 'Illinois'), ('CT', 'Connecticut'), ('ME', 'Maine'), ('TX', 'Texas'), ('VT', 'Vermont')], max_length=100),
        ),
    ]
