# Generated by Django 4.0.3 on 2022-03-15 18:58

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_created_date_alter_car_doors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 15, 19, 58, 43, 994367)),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('3', '3'), ('2', '2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Direct Fuel Injection', 'Direct Fuel Injection'), ('Air Conditioning', 'Air Conditioning'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Reversing Camera', 'Reversing Camera'), ('Cruise Control', 'Cruise Control'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Seat Heating', 'Seat Heating'), ('ParkAssist', 'ParkAssist'), ('Alarm System', 'Alarm System'), ('Airbags', 'Airbags'), ('Power Steering', 'Power Steering'), ('Audio Interface', 'Audio Interface')], max_length=195),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('WA', 'Washington'), ('SD', 'South Dakota'), ('VT', 'Vermont'), ('AK', 'Alaska'), ('MD', 'Maryland'), ('MS', 'Mississippi'), ('OR', 'Oregon'), ('MN', 'Minnesota'), ('IN', 'Indiana'), ('ID', 'Idaho'), ('KS', 'Kansas'), ('MI', 'Michigan'), ('MO', 'Missouri'), ('PA', 'Pennsylvania'), ('ME', 'Maine'), ('CO', 'Colorado'), ('DE', 'Delaware'), ('AL', 'Alabama'), ('NJ', 'New Jersey'), ('AZ', 'Arizona'), ('OH', 'Ohio'), ('ND', 'North Dakota'), ('SC', 'South Carolina'), ('HI', 'Hawaii'), ('NE', 'Nebraska'), ('WY', 'Wyoming'), ('VA', 'Virginia'), ('MT', 'Montana'), ('UT', 'Utah'), ('WV', 'West Virginia'), ('NH', 'New Hampshire'), ('IA', 'Iowa'), ('FL', 'Florida'), ('KY', 'Kentucky'), ('TX', 'Texas'), ('AR', 'Arkansas'), ('DC', 'District Of Columbia'), ('GA', 'Georgia'), ('NC', 'North Carolina'), ('MA', 'Massachusetts'), ('NV', 'Nevada'), ('OK', 'Oklahoma'), ('IL', 'Illinois'), ('LA', 'Louisiana'), ('CA', 'California'), ('CT', 'Connecticut'), ('RI', 'Rhode Island'), ('NM', 'New Mexico'), ('TN', 'Tennessee'), ('NY', 'New York'), ('WI', 'Wisconsin')], max_length=100),
        ),
    ]
